server:
  port: 8080
  servlet:
    context-path: /docker-pass-env-var-to-container

app:
  name: env-app # will be changed

spring:
  profiles:
    active: ${PROFILE:prd} # will be changed
  datasource:
    url: jdbc:mysql://localhost:3306/test # will be changed

management:
  endpoint:
    health:
      show-components: always
  endpoints:
    web:
      base-path: /v1/actuator # will be changed
      exposure:
        include: actuator,logfile,metrics,health,info