version: '3.8'
services:
  env-app:
    image: configs-app:latest
    ports:
      - "8080:8080"
    volumes:
      - ./configurations:/configurations
    environment:
      JAVA_OPTS: -Dspring.config.location=/configurations/application.yaml