version: '3.8'
services:
  env-app:
    image: configs-app:latest
    ports:
      - "8080:8080"
    volumes:
      - ./configurations:/configurations
    environment:
      ARGS: --spring.config.location=/configurations/application-args.yaml